API-12152 lc sdk js verify required and optional fields of structures v4
livechat/lc-sdk-js pull request #113
Opened 2023-03-07 11:23 UTC by maciejjwojcik

2023-03-08 14:08 UTC, wfabjanczuk requested changes

2023-03-08 14:08 UTC, wfabjanczuk commented on src/agent/structures/structures.ts
> +  filters: ArchivesFilters;
```suggestion
  filters?: ArchivesFilters;
```
It should be optional like in newer versions

2023-03-08 14:08 UTC, wfabjanczuk commented on src/agent/structures/structures.ts
> +  highlights: Highlights
```suggestion
  highlights?: Highlights
```
It should be optional like in newer versions

2023-03-08 14:08 UTC, wfabjanczuk commented on src/agent/structures/structures.ts
> +  id: string;
```suggestion
```
As explained in PR for v3.5, this should not be here because chat id is passed in the method parameter:
https://github.com/livechat/lc-sdk-js/blob/997069a381eb1c181a95ead908ec5dbd41585431/src/agent/rtm.ts#L178

2023-03-08 14:08 UTC, wfabjanczuk commented on src/customer/structures/responses.ts
> +  found_chats: number;
```suggestion
```
In customer api it is `total_chats`, this line should be reverted

Also let's not change anything in customer api now

2023-03-24 13:40 UTC, maciejjwojcik commented on src/agent/structures/structures.ts
> +  filters: ArchivesFilters;
OK in v3.5

2023-03-24 13:41 UTC, maciejjwojcik commented on src/agent/structures/structures.ts
> +  highlights: Highlights
OK in v3.5

2023-03-24 13:42 UTC, maciejjwojcik commented on src/agent/structures/structures.ts
> +  id: string;
Done in v3.5

2023-03-24 13:43 UTC, maciejjwojcik commented on src/customer/structures/responses.ts
> +  found_chats: number;
OK in v3.5, 3.6
fixed in v3.3, v3.4

2023-04-06 15:51 UTC, wfabjanczuk approved these changes

2023-04-06 16:45 UTC, merged