API-12152 lc sdk js verify required and optional fields of structures v6
livechat/lc-sdk-js pull request #115
Opened 2023-03-07 11:24 UTC by maciejjwojcik

2023-03-08 12:44 UTC, wfabjanczuk requested changes

2023-03-08 12:44 UTC, wfabjanczuk commented on src/agent/structures/structures.ts
> +  greetings_Accepted_count: number;
the same typo in all versions
```suggestion
  greetings_accepted_count: number;
```

2023-03-24 13:31 UTC, maciejjwojcik commented on src/agent/structures/structures.ts
> +  greetings_Accepted_count: number;
I'll use the comment to mark fixes in various versions:
Fixed for v3.5

2023-04-06 16:57 UTC, wfabjanczuk approved these changes

2023-04-06 16:59 UTC, closed without merging