Alignment for V3.4
livechat/lc-sdk-js pull request #35
Opened 2021-05-25 14:22 UTC by grz-gajda

2021-05-25 15:38 UTC, kogierman approved these changes
lgtm

2021-05-26 08:36 UTC, janowsiany requested changes

2021-05-26 14:36 UTC, grz-gajda commented on src/objects/index.ts
> -export interface Thread {
There were two `Thread` interfaces in one file. They were overlapping themselves. The second `Thread` interface contains all necessary fields provided by API v3.3.

2021-05-26 14:54 UTC, janowsiany approved these changes

2021-05-27 10:15 UTC, kogierman approved these changes

2021-06-10 13:58 UTC, merged