API-9153 Strictly typed list_archives filters
livechat/lc-sdk-js pull request #39
Opened 2021-07-14 13:30 UTC by janowsiany

2021-07-15 09:32 UTC, grz-gajda requested changes

2021-07-15 09:32 UTC, grz-gajda commented on src/agent/structures.ts
> +  filters?: ArchivesFilters;
`ArchiveFilters` has required fields e.g. `agents`, `tags` etc. Before when we have `object` there developers could create any kind of object and type it `ArchivesFilters` manually:

```typescript
const p: ListArchivesParameters = { filters: {} as Partial<ArchiveFilters> };
```

Currently `ListArchivesParameters` needs to get `ArchivesFilters` (of course optionally, but still) and `ArchivesFilters` has many non-optional fields which really are optional in agent-api. I think you could type

```typescript
export interface ListArchivesParameters {
  filters?: Partial<ArchiveFilters>;
}
```

or set these fields optional.

2021-07-16 07:36 UTC, grz-gajda approved these changes

2021-07-19 09:35 UTC, kogierman approved these changes

2021-07-22 09:11 UTC, merged