API-10240 add support for list_channels and get_product_limits_for_plan
livechat/lc-sdk-js pull request #58
Opened 2022-04-19 06:34 UTC by MaciejSzaflik

Added support for list_channels and check_product_limits_for_plan

2022-04-25 10:35 UTC, grz-gajda approved these changes

2022-04-25 10:35 UTC, grz-gajda commented on src/configuration/structures.ts
> +	id?:        string;
Please fix the formatting.

2022-04-25 10:35 UTC, grz-gajda commented on src/configuration/index.ts
> +   async checkProductLimitsForPlan(plan: string): Promise<PlanLimit[]> {
Please fix the formatting.

2022-04-25 10:36 UTC, grz-gajda requested changes

2022-04-25 10:36 UTC, grz-gajda commented on src/configuration/index.ts
> +   async checkProductLimitsForPlan(plan: string): Promise<PlanLimit[]> {
Please fix the formatting.

2022-04-25 10:36 UTC, grz-gajda commented
The first approve was the missclick 👀  .

2022-04-26 16:25 UTC, MaciejSzaflik commented on src/configuration/structures.ts
> +	id?:        string;
tabs removed, spaces removed

2022-04-26 16:26 UTC, MaciejSzaflik commented on src/configuration/index.ts
> +   async checkProductLimitsForPlan(plan: string): Promise<PlanLimit[]> {
space removed

2022-04-29 07:48 UTC, grz-gajda approved these changes

2022-05-06 06:34 UTC, merged